import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { collection, QueryDocumentSnapshot, DocumentData, query, where, onSnapshot, QuerySnapshot, orderBy, Unsubscribe } from 'firebase/firestore'
import { firestore } from '../firebase/clientApp'
import Card from '../components/Card'
import {Swiper, SwiperSlide} from 'swiper/react'
import { EffectCards } from 'swiper'
import 'swiper/css'
import 'swiper/css/effect-cards'
import { getAuth } from 'firebase/auth'

const Done: NextPage = () => {

  const auth = getAuth()
  const uid = auth.currentUser ? auth.currentUser.uid : ''

  const todosColletion = collection(firestore, 'todos')
  const [todos, setTodos] = useState<QueryDocumentSnapshot<DocumentData>[]>([])
  const [loading, setLoading] = useState<boolean>(true)
  let unsub: Unsubscribe

  const getTodos = async () => {
    const todosQuery = query(todosColletion, where('done', '==', true), where('uid','==', uid), orderBy('timestamp', 'desc'))
    
      unsub = onSnapshot(todosQuery, (snapshot: QuerySnapshot) => {
      const result : QueryDocumentSnapshot<DocumentData>[] = []
      snapshot.forEach((doc: QueryDocumentSnapshot) => result.push(doc))
      setTodos(result)
      setLoading(false)
    })
  }

  useEffect( () => {
    getTodos()

    return () => {
      unsub()
    }
  }, [])

  return (
    <div className='bg-emerald-500 w-full min-h-screen flex flex-col items-center justify-between py-4'>
      <Head>
        <title>Todo Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-center text-slate-200 text-2xl font-black mb-4'>Todo List</h1>
      <div className='w-80'>

        {
          loading ? (
          <div className='text-lg font-bold text-center text-slate-200'>
            ...loading
          </div>) :
          todos.length === 0 ? 
          (<div className='text-lg font-bold text-center text-slate-200'>No data yet...</div>) :
          (
            <Swiper
              modules={[EffectCards]}
              width={320}
              effect={'cards'}
              loop={true}
              grabCursor={true}
            >
              {
                todos.map( (todo, index) => (
                  <SwiperSlide key={index} className='rounded-2xl overflow-hidden' >
                    <Card todo={todo} />
                  </SwiperSlide>
                ) )
              }
            </Swiper>
          )
        }
      </div>
      <div className='h-36'></div>
    </div>
  )
}

export default Done
